Update to make roboptim-core compiled with Humble
roboptim/roboptim-core pull request #128
Opened 2024-10-27 17:47 UTC by olivier-stasse

In order to make this repository compiled with humble:
- Update submodule
- Update package.xml
- Update CMakeLists.txt

Tested on Humble.

2025-01-09 12:27 UTC, nim65s commented on include/roboptim/core/detail/utility.hh
> +# include <eigen3/Eigen/Core>
On my 24.04, `/usr/share/eigen3/cmake/Eigen3Targets.cmake` contains:
```cmake
set_target_properties(Eigen3::Eigen PROPERTIES
  INTERFACE_INCLUDE_DIRECTORIES "${_IMPORT_PREFIX}/include/eigen3"
)
```

Therefore, if you link your libraries to the `Eigen3::Eigen` CMake export, you don't need to add this `eigen3/` to your c++ `#include <…>`

2025-01-09 12:30 UTC, nim65s commented on CMakeLists.txt
> +SET(CMAKE_CXX_STANDARD 14)
This will break things on systems where the default compiler will default to C++ >= 17. Please use https://github.com/jrl-umi3218/jrl-cmakemodules/blob/master/cxx-standard.cmake instead.

2025-01-09 12:30 UTC, nim65s commented on CMakeLists.txt
> +SET(USE_CXX11 TRUE CACHE BOOL "Whether to use C++11")
This will hardcode the `-std=c++11` flag, breaking things for compilers which default to C++ >= 14

2025-01-09 12:31 UTC, nim65s commented on package.xml
> +  <version>0.1.0</version>
```suggestion
  <version>3.2</version>
```

2025-01-09 12:31 UTC, nim65s commented on package.xml
> +  <license>BSD</license>
This package is GPL3 / LGPL3

2025-01-09 12:32 UTC, nim65s requested changes
Sorry I sent many "single comments" instead of making a proper complete review

2025-03-15 06:45 UTC, olivier-stasse commented on CMakeLists.txt
> +SET(CMAKE_CXX_STANDARD 14)
Fixed with commit 6ee4ee5

2025-03-15 06:45 UTC, olivier-stasse commented on CMakeLists.txt
> +SET(USE_CXX11 TRUE CACHE BOOL "Whether to use C++11")
Fixed with commit 6ee4ee5

2025-03-15 06:47 UTC, olivier-stasse commented on package.xml
> +  <license>BSD</license>
Fixed with commit d14d6d7

2025-03-15 08:00 UTC, olivier-stasse commented
@nim65s all comments were addressed and tested on Jazzy.

2025-03-17 09:53 UTC, nim65s requested changes

2025-03-17 09:53 UTC, nim65s commented on tests/CMakeLists.txt
> +    ${NAME} PUBLIC
```suggestion
    ${NAME} PRIVATE
```

2025-03-17 10:42 UTC, olivier-stasse commented on tests/CMakeLists.txt
> +    ${NAME} PUBLIC
Fixed with commit f902235

2025-03-17 10:42 UTC, olivier-stasse commented on include/roboptim/core/detail/utility.hh
> +# include <eigen3/Eigen/Core>
Fixed with 2d9847d

2025-03-17 12:10 UTC, nim65s requested changes

2025-03-17 12:10 UTC, nim65s commented on include/roboptim/core/detail/utility.hh
> +# include <eigen3/Eigen/Core>
The issue was not about `Eigen/Stdvector` in particular, but with the `<Eigen/xxx>` -> `<eigen3/Eigen/xxx>` change : The correct way of including Eigen things is the former, so the changes in this PR on this topic are going in the wrong direction

2025-03-17 17:48 UTC, olivier-stasse commented on include/roboptim/core/detail/utility.hh
> +# include <eigen3/Eigen/Core>
Sorry, for some reason your comment on my commit hit my brain as a suggestion...
... commit 8c353f83 should provide what is expected.

2025-03-17 18:54 UTC, nim65s commented on include/roboptim/core/function.hh
> +# include <eigen3/Eigen/Sparse>
You still have extras `eigen3/` here and in other files 😅

2025-03-18 06:24 UTC, olivier-stasse commented on include/roboptim/core/function.hh
> +# include <eigen3/Eigen/Sparse>
Sorrrry. Fixed in  ca16c3e.
While being at it, fixed warnings.

2025-03-18 11:06 UTC, nim65s approved these changes

2025-03-21 07:22 UTC, merged